### ISSUE TITLE
How to receive access token with example code by default receiving IDToken

### ISSUE THREAD

**Issue by mbhusari** [mohanajuhi166/aad-b2c-webview#1]
1. Included plugin and used ADB2CEmbedWebView sample code for receiving access_token
2. But by default callback is coming in onIDToken,
3. Tried declaring responseType as 'access_token' but it is not supported.
What is the correct responseType for access_token

**Comment by furkansoylemez** [comment]
same issue here

**Comment by jaym-xa** [comment]
@furkansoylemez @mbhusari Let me know if you have found any solution for this one? I'm also facing the same issue.

**Comment by furkansoylemez** [comment]
@jaym-xa i removed package and implemented same flow myself because It doesn't look like a well maintained package.

**Comment by mohanajuhi166** [comment]
@jaym-xa @furkansoylemez @mbhusar, the official repository is here: https://github.com/microsoft/aad_b2c_webview

We will start maintaining this repository. Can you kindly report the issue there? 

Thanks.

**Comment by jaym-xa** [comment]
@mohanajuhi166 Ok I've raised already query on this issue, Please do check and update

(https://github.com/microsoft/aad_b2c_webview/issues/9)

**Comment by mohanajuhi166** [comment]
PR has been raised: https://github.com/microsoft/aad_b2c_webview/pull/11

**Comment by mohanajuhi166** [comment]
this has been resolved in above PR
