### ISSUE TITLE
Incorrect scope used when requesting access tokens

### ISSUE THREAD

**Issue by furkansoylemez** [mohanajuhi166/aad-b2c-webview#4]
Hello,

I'm currently utilizing this library in a project and I've encountered an issue where the access token is not being received.

When the library opens the sign-in page, it correctly uses the scopes I provide. However, in the getAllTokens function, the scopes are hardcoded to openid and offline_access rather than utilizing the scopes that were passed in.

This is the current implementation in the getAllTokens function:

> Future<AzureTokenResponse?> getAllTokens({
...
    String scopes = Constants.defaultScopes, //problem is here
...
  }) async {
    //...
  }

  
  Since the scope constant to 'openid profile offline_access', the library only fetches id_token and refresh_token but not the access_token.
  
  The scope parameter in the post request data should be set to the scope provided, which can be done by passing it as a parameter to the getAllTokens function. If no scope is provided, then it can default to 'openid offline_access'.
  
  Thank you for your attention to this issue. Please let me know if any more information is needed.

**Comment by mohanajuhi166** [comment]
hey @furkansoylemez  we have an official repository here: https://github.com/microsoft/aad_b2c_webview

Apologies for looking at this now. Can you add the issue there and we will look into it?

Thanks again

**Comment by mohanajuhi166** [comment]
PR has been raised here: https://github.com/microsoft/aad_b2c_webview/pull/11

**Comment by mohanajuhi166** [comment]
this has resolved in above mentioned PR.
